import { serve } from 'https://deno.land/std@0.224.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type', 'Access-Control-Allow-Methods': 'POST, OPTIONS' }
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, 'content-type': 'application/json' } })
async function hmac(key: Uint8Array, message: string) { const k = await crypto.subtle.importKey('raw', key, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']); return new Uint8Array(await crypto.subtle.sign('HMAC', k, new TextEncoder().encode(message))) }
async function sha256(value: string) { return new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value))) }
function hex(bytes: Uint8Array) { return [...bytes].map(b => b.toString(16).padStart(2, '0')).join('') }
function hexToUuid(h: string) { const x = h.slice(0, 32); return `${x.slice(0,8)}-${x.slice(8,12)}-5${x.slice(13,16)}-8${x.slice(17,20)}-${x.slice(20,32)}` }
async function stableUuid(id: number) { return hexToUuid(hex(await sha256(`pochemuchka:telegram:${id}`))) }
async function telegramUser(initData: string, token: string) { const p = new URLSearchParams(initData), hash = p.get('hash'), authDate = Number(p.get('auth_date') || 0), now = Math.floor(Date.now() / 1000); p.delete('hash'); if (!hash || !authDate || now - authDate > 86400 || now < authDate - 60) throw new Error('invalid or expired initData'); const data = [...p.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `${k}=${v}`).join('\n'); const secret = await hmac(new TextEncoder().encode('WebAppData'), token); if (hex(await hmac(secret, data)) !== hash) throw new Error('invalid Telegram signature'); const user = JSON.parse(p.get('user') || 'null'); if (!user?.id) throw new Error('Telegram user missing'); return user }
function secretKey() { const keys = Deno.env.get('SUPABASE_SECRET_KEYS'); if (keys) { try { const parsed = JSON.parse(keys); if (parsed.default) return parsed.default } catch {} } return Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || '' }
serve(async req => { if (req.method === 'OPTIONS') return new Response('ok', { headers: cors }); try { const token = Deno.env.get('TELEGRAM_BOT_TOKEN'), url = Deno.env.get('SUPABASE_URL'), key = secretKey(); if (!token || !url || !key) return json({ error: 'server not configured' }, 500); const { initData, action, payload = {} } = await req.json(); const user = await telegramUser(String(initData || ''), token); const admin = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); const userId = await stableUuid(Number(user.id));
if (action === 'bootstrap') { const { data: profile, error: pe } = await admin.from('profiles').select('*').eq('user_id', userId).maybeSingle(); if (pe) throw pe; const { data: progress, error } = profile ? await admin.from('lesson_progress').select('*').eq('profile_id', profile.id) : { data: [], error: null }; if (error) throw error; return json({ ok: true, telegramUser: user, profile, progress: progress || [] }) }
if (action === 'save_profile') { const age = Number(payload.age), name = String(payload.name || '').trim().slice(0, 40), avatar = String(payload.avatar || '🐱').slice(0, 8); if (!name || age < 6 || age > 10) return json({ error: 'invalid profile' }, 400); const { error: ue } = await admin.from('telegram_users').upsert({ id: userId, telegram_id: Number(user.id), first_name: user.first_name || null, last_name: user.last_name || null, username: user.username || null, updated_at: new Date().toISOString() }, { onConflict: 'telegram_id' }); if (ue) throw ue; const { data, error } = await admin.from('profiles').upsert({ user_id: userId, name, age, avatar, updated_at: new Date().toISOString() }, { onConflict: 'user_id' }).select().single(); if (error) throw error; return json({ ok: true, profile: data }) }
const { data: profile, error: profileError } = await admin.from('profiles').select('id').eq('user_id', userId).single(); if (profileError || !profile) return json({ error: 'profile not found' }, 404)
if (action === 'save_progress') { const lessonId = String(payload.lessonId || ''), status = String(payload.status || ''); if (!lessonId || !['in_progress', 'completed'].includes(status)) return json({ error: 'invalid progress' }, 400); const { count: total, error: countError } = await admin.from('activities').select('id', { count: 'exact', head: true }).eq('lesson_id', lessonId); if (countError) throw countError; const totalSteps = Math.max(1, total || 1), score = Math.max(0, Math.min(totalSteps, Math.floor(Number(payload.score || 0)))); if (status === 'in_progress') { const { data, error } = await admin.from('lesson_progress').upsert({ profile_id: profile.id, lesson_id: lessonId, status, score, mastery: 0, attempts: Math.max(0, Math.floor(Number(payload.attempts || 0))), started_at: payload.startedAt || new Date().toISOString(), xp: 0, stars: 0 }, { onConflict: 'profile_id,lesson_id' }).select().single(); if (error) throw error; return json({ ok: true, progress: data }) } const accuracy = score / totalSteps, stars = accuracy >= .9 ? 3 : accuracy >= .6 ? 2 : accuracy >= .3 ? 1 : 0, rewardKey = `lesson:${lessonId}:completion`; const { data: reward } = await admin.from('reward_transactions').select('amount').eq('profile_id', profile.id).eq('reward_key', rewardKey).maybeSingle(); const xp = reward ? 0 : 20 + score * 10; if (!reward) { const { error: re } = await admin.from('reward_transactions').insert({ profile_id: profile.id, reward_key: rewardKey, amount: xp }); if (re && re.code !== '23505') throw re } const { data: existing } = await admin.from('lesson_progress').select('xp,stars,attempts,started_at').eq('profile_id', profile.id).eq('lesson_id', lessonId).maybeSingle(); const storedXp = existing?.xp || xp, storedStars = existing?.stars || stars; const { data, error } = await admin.from('lesson_progress').upsert({ profile_id: profile.id, lesson_id: lessonId, status: 'completed', score, mastery: accuracy, attempts: (existing?.attempts || 0) + 1, started_at: payload.startedAt || existing?.started_at || null, completed_at: new Date().toISOString(), xp: storedXp, stars: storedStars }, { onConflict: 'profile_id,lesson_id' }).select().single(); if (error) throw error; return json({ ok: true, progress: data }) }
if (action === 'attempt') { const activityId = String(payload.activityId || ''), isCorrect = Boolean(payload.isCorrect); if (!activityId) return json({ error: 'activityId required' }, 400); const { data: activity, error: ae } = await admin.from('activities').select('id,lesson_id').eq('id', activityId).maybeSingle(); if (ae) throw ae; if (!activity) return json({ error: 'activity not found' }, 404); const { data, error } = await admin.from('activity_attempts').insert({ profile_id: profile.id, activity_id: activityId, is_correct: isCorrect, answer: payload.answer ?? null, time_spent: payload.timeSpent ?? null }).select().single(); if (error) throw error; return json({ ok: true, attempt: data }) }\nif (action === 'analytics') { const eventName = String(payload.eventName || '').slice(0, 80); if (!eventName) return json({ error: 'eventName required' }, 400); const { error } = await admin.from('analytics_events').insert({ profile_id: profile.id, event_name: eventName, payload: payload.payload || {} }); if (error) throw error; return json({ ok: true }) }
return json({ error: 'unknown action' }, 400) } catch (e) { return json({ error: e instanceof Error ? e.message : String(e) }, 400) } })
