-- POCHEMUЧКА: age-appropriate curriculum language pass.
-- Keeps the 200-question structure but simplifies terminology, explanations, and examples for the target age.
-- Source of truth: src/content/content.ts

  update activities set content = '{"question":"Откуда берутся облака?","answers":[{"id":"0","text":"Вода поднимается в воздух, остывает и превращается в крошечные капельки."},{"id":"1","text":"Из дыма деревьев"},{"id":"2","text":"Из растаявшего снега прямо в небе"}],"correctAnswerId":"0","explanation":"Когда водяной пар остывает высоко в небе, появляются маленькие капельки воды — из них образуются облака."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'nature-1-07';
  update activities set content = '{"question":"Почему небо кажется голубым?","answers":[{"id":"0","text":"Потому что облака отражают синюю краску"},{"id":"1","text":"Солнечный свет проходит через воздух, и синий цвет рассеивается сильнее."},{"id":"2","text":"Потому что в небе есть синяя вода"}],"correctAnswerId":"1","explanation":"Воздух рассеивает солнечный свет. Синий цвет рассеивается сильнее, поэтому небо кажется голубым."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'nature-2-02';
  update activities set content = '{"question":"Почему у снежинок часто бывает шесть лучей?","answers":[{"id":"0","text":"Так устроены маленькие кристаллы льда, из которых растёт снежинка."},{"id":"1","text":"Потому что у всех облаков шесть сторон"},{"id":"2","text":"Потому что ветер рисует лучи"}],"correctAnswerId":"0","explanation":"Вода при замерзании образует кристаллы особой формы. Поэтому у снежинок часто появляется шесть лучей."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'nature-2-09';
  update activities set content = '{"question":"Почему летом день длиннее, чем зимой?","answers":[{"id":"0","text":"Потому что Земля летом вращается медленнее"},{"id":"1","text":"Потому что Солнце летом становится больше"},{"id":"2","text":"Летом наша часть Земли дольше освещена Солнцем."}],"correctAnswerId":"2","explanation":"Земная ось наклонена. Поэтому в разные времена года Солнце освещает нашу часть Земли разное количество часов."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'nature-2-01';
  update activities set content = '{"question":"Почему меняются времена года?","answers":[{"id":"0","text":"Потому что Солнце каждый месяц меняет размер"},{"id":"1","text":"Потому что Земля останавливается зимой"},{"id":"2","text":"Земля движется вокруг Солнца, а её ось немного наклонена."}],"correctAnswerId":"2","explanation":"Из-за наклона земной оси разные части Земли в течение года получают разное количество солнечного света."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'nature-2-07';
  update activities set content = '{"question":"Почему летом обычно теплее, чем зимой?","answers":[{"id":"0","text":"Летом Солнце выше над горизонтом и дольше светит."},{"id":"1","text":"Потому что Солнце приближается к Земле в июле"},{"id":"2","text":"Потому что зимой Земля перестаёт вращаться"}],"correctAnswerId":"0","explanation":"Летом наша часть Земли получает больше солнечного тепла: день длиннее, а солнечные лучи падают более прямо."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'nature-2-03';
  update activities set content = '{"question":"Как растения получают питание?","answers":[{"id":"0","text":"С помощью света, воды и воздуха растения сами создают себе питание."},{"id":"1","text":"Они едят почву как животные"},{"id":"2","text":"Они получают готовую пищу только от насекомых"}],"correctAnswerId":"0","explanation":"Зелёные растения используют свет, воду и углекислый газ из воздуха, чтобы создавать питательные вещества."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'animals-2-01';
  update activities set content = '{"question":"Почему растениям необходим свет?","answers":[{"id":"0","text":"Свет заменяет корни"},{"id":"1","text":"Свет нужен только цветам"},{"id":"2","text":"Свет помогает растениям создавать питательные вещества."}],"correctAnswerId":"2","explanation":"Растения используют свет, чтобы создавать питательные вещества из воды и углекислого газа."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'animals-2-05';
  update activities set content = '{"question":"Что такое симметрия?","answers":[{"id":"0","text":"Любая неровная форма"},{"id":"1","text":"Только круг"},{"id":"2","text":"Когда две части фигуры похожи друг на друга как отражение в зеркале."}],"correctAnswerId":"2","explanation":"Например, у бабочки левая и правая стороны похожи. Такое расположение называют симметрией."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'math-2-14';
  update activities set content = '{"question":"Что такое атмосфера?","answers":[{"id":"0","text":"Слой горных пород"},{"id":"1","text":"Только облака"},{"id":"2","text":"Слой воздуха вокруг Земли."}],"correctAnswerId":"2","explanation":"Атмосфера — это воздух вокруг нашей планеты. Она помогает сохранять условия, необходимые для жизни."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'nature-3-09';
  update activities set content = '{"question":"Что такое эрозия почвы?","answers":[{"id":"0","text":"Когда вода или ветер постепенно уносят верхний слой почвы."},{"id":"1","text":"Рост новых растений"},{"id":"2","text":"Замерзание воды в почве"}],"correctAnswerId":"0","explanation":"Сильный ветер и вода могут уносить частицы земли. Поэтому верхний слой почвы становится тоньше."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'nature-3-05';
  update activities set content = '{"question":"Что такое экосистема?","answers":[{"id":"0","text":"Только участок леса без живых организмов"},{"id":"1","text":"Место, где растения, животные и неживая природа связаны между собой."},{"id":"2","text":"Только группа животных одного вида"}],"correctAnswerId":"1","explanation":"Например, в лесу деревья, животные, насекомые, вода и почва влияют друг на друга."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'nature-3-07';
  update activities set content = '{"question":"Что такое опыление?","answers":[{"id":"0","text":"Перенос пыльцы с одного цветка на другой или внутри цветка."},{"id":"1","text":"Перенос воды в корни"},{"id":"2","text":"Рост листьев"}],"correctAnswerId":"0","explanation":"Пыльца помогает растению образовать семена. Перенос пыльцы называют опылением."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'animals-3-03';
  update activities set content = '{"question":"Что такое фотосинтез?","answers":[{"id":"0","text":"Процесс превращения листьев в почву"},{"id":"1","text":"Процесс, с помощью которого зелёные растения на свету создают питательные вещества из воды и углекислого газа."},{"id":"2","text":"Процесс дыхания только ночью"}],"correctAnswerId":"1","explanation":"Проще говоря, растение использует свет, воду и углекислый газ, чтобы создать себе питание."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'animals-3-05';
  update activities set content = '{"question":"Что такое симбиоз?","answers":[{"id":"0","text":"Любая борьба между животными"},{"id":"1","text":"Когда два разных живых организма живут рядом и получают пользу друг от друга."},{"id":"2","text":"Жизнь только одного организма"}],"correctAnswerId":"1","explanation":"Например, пчела получает нектар, а цветок помогает пчеле найти пищу и переносить пыльцу."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'animals-3-11';
  update activities set content = '{"question":"Что такое инстинктивное поведение?","answers":[{"id":"0","text":"Действие, которое животное умеет выполнять от рождения."},{"id":"1","text":"Поведение, которому всегда учат люди"},{"id":"2","text":"Любое случайное действие"}],"correctAnswerId":"0","explanation":"Например, маленький паучок умеет плести паутину без уроков человека."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'animals-3-15';
  update activities set content = '{"question":"Что такое эпитет?","answers":[{"id":"0","text":"Красивое или образное слово, которое помогает ярче описать предмет."},{"id":"1","text":"Любое число в тексте"},{"id":"2","text":"Знак препинания"}],"correctAnswerId":"0","explanation":"Например, в выражении «золотая осень» слово «золотая» делает описание ярче."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'language-3-10';
  update activities set content = '{"question":"Что такое кульминация?","answers":[{"id":"0","text":"Список персонажей"},{"id":"1","text":"Самый напряжённый и важный момент в истории."},{"id":"2","text":"Первое слово произведения"}],"correctAnswerId":"1","explanation":"Это момент, когда происходит главное событие и напряжение истории становится самым сильным."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'language-3-15';
  update activities set content = '{"question":"Что такое архаизмы?","answers":[{"id":"0","text":"Новые слова из интернета"},{"id":"1","text":"Только имена людей"},{"id":"2","text":"Слова, которые раньше часто использовали, а сейчас почти не используют."}],"correctAnswerId":"2","explanation":"Такие слова можно встретить в старых книгах и исторических текстах."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'language-3-17';
  update activities set content = '{"question":"Что такое фразеологизм?","answers":[{"id":"0","text":"Обычное предложение без переносного смысла"},{"id":"1","text":"Устойчивое выражение, которое имеет особый, часто переносный смысл."},{"id":"2","text":"Любое длинное слово"}],"correctAnswerId":"1","explanation":"Например, «бить баклуши» значит бездельничать, а не буквально что-то бить."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'language-3-18';
  update activities set content = '{"question":"Что такое периметр?","answers":[{"id":"0","text":"Площадь внутри фигуры"},{"id":"1","text":"Количество углов"},{"id":"2","text":"Длина всей границы фигуры — если сложить длины всех её сторон."}],"correctAnswerId":"2","explanation":"Например, у квадрата со стороной 3 см периметр равен 3 + 3 + 3 + 3 = 12 см."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'math-3-04';
  update activities set content = '{"question":"Что такое площадь?","answers":[{"id":"0","text":"Количество вершин"},{"id":"1","text":"Сколько места занимает фигура на плоскости."},{"id":"2","text":"Длина одной стороны"}],"correctAnswerId":"1","explanation":"Например, площадь показывает, сколько квадратных сантиметров занимает прямоугольник."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'math-3-05';
  update activities set content = '{"question":"Что такое дробь?","answers":[{"id":"0","text":"Только целое число больше 100"},{"id":"1","text":"Название геометрической фигуры"},{"id":"2","text":"Число, которое показывает часть целого."}],"correctAnswerId":"2","explanation":"Например, 1/2 — это одна из двух равных частей целого, то есть половина."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'math-3-07';
  update activities set content = '{"question":"Что такое координатная сетка?","answers":[{"id":"0","text":"Сетка из линий или клеток, которая помогает найти место точки."},{"id":"1","text":"Таблица умножения"},{"id":"2","text":"Список геометрических фигур"}],"correctAnswerId":"0","explanation":"По координатам можно точно сказать, где находится точка на сетке."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'math-3-15';
  update activities set content = '{"question":"Что такое диаграмма?","answers":[{"id":"0","text":"Только геометрическая фигура"},{"id":"1","text":"Рисунок или схема, которая помогает показать и сравнить данные."},{"id":"2","text":"Любой рисунок без данных"}],"correctAnswerId":"1","explanation":"Например, столбики на диаграмме могут показать, сколько книг прочитали разные дети."}'::jsonb, config = '{"xp":10,"answerOrderVersion":1}'::jsonb where id = 'math-3-17';

do $$
declare v_bad int;
begin
  select count(*) into v_bad
  from activities a
  join lessons l on l.id = a.lesson_id
  where l.is_active and a.type = 'quiz'
    and (jsonb_array_length(a.content->'answers') <> 3
      or coalesce(length(a.content->>'explanation'),0) < 15);
  if v_bad <> 0 then
    raise exception 'Age-appropriate curriculum integrity failed: bad quiz rows=%', v_bad;
  end if;

  if (select count(*) from activities a join lessons l on l.id=a.lesson_id where l.is_active and a.type='quiz') <> 200 then
    raise exception 'Age-appropriate curriculum integrity failed: active quiz count is not 200';
  end if;
end $$;
